name: gtab-py
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.11.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py310h29418f3_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h179d6b4_5
  - aws-c-cal=0.9.8=ha82e055_0
  - aws-c-common=0.12.5=hfd05255_1
  - aws-c-compression=0.3.1=h83e01e5_7
  - aws-c-event-stream=0.5.6=hd31a2bc_4
  - aws-c-http=0.10.7=h4b68edd_1
  - aws-c-io=0.23.2=h460b297_2
  - aws-c-mqtt=0.13.3=hfde8714_8
  - aws-c-s3=0.8.6=haf2eb35_7
  - aws-c-sdkutils=0.2.4=h83e01e5_2
  - aws-checksums=0.2.7=h83e01e5_3
  - aws-crt-cpp=0.35.0=hd7c148e_2
  - aws-sdk-cpp=1.11.606=h2b076a5_6
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=hfd34d9b_1
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - brotli-python=1.2.0=py310h8abc2a3_0
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.5=h2466b09_0
  - c-blosc2=2.15.2=h9e57077_1
  - ca-certificates=2025.11.12=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310h29418f3_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310hc19bc0b_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.17=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - duckdb=1.4.1=hca7485f_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py310hdb0e946_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=h57928b3_0
  - freexl=2.0.0=hf297d47_2
  - geopandas=1.1.1=pyhd8ed1ab_1
  - geopandas-base=1.1.1=pyha770c72_1
  - geos=3.14.0=hdade9fe_0
  - glib=2.86.1=hde84fb4_2
  - glib-tools=2.86.1=he647baa_2
  - graphite2=1.3.14=hac47afa_2
  - greenlet=3.2.4=py310h73ae2b4_1
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h5f2951f_0
  - hdf5=1.14.4=nompi_hd5d9e70_105
  - hpack=4.1.0=pyhd8ed1ab_0
  - html5lib=1.1=pyhd8ed1ab_2
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310h5588dad_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.10=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.4=h20038f6_0
  - libarchive=3.8.2=gpl_h26aea39_100
  - libarrow=22.0.0=h0832232_3_cpu
  - libarrow-acero=22.0.0=h7d8d6a5_3_cpu
  - libarrow-compute=22.0.0=h2db994a_3_cpu
  - libarrow-dataset=22.0.0=h7d8d6a5_3_cpu
  - libarrow-substrait=22.0.0=hf865cc0_3_cpu
  - libblas=3.9.0=35_h5709861_mkl
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libclang13=21.1.5=default_ha2db4b5_0
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.24=h76ddb4d_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libgdal-core=3.11.4=h64ee9a2_1
  - libglib=2.86.1=hd9c3897_2
  - libgomp=15.2.0=h1383e82_7
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.1=hac9b6f3_5
  - libkml=1.3.0=h68a222c_1022
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libogg=1.3.5=h2466b09_1
  - libparquet=22.0.0=h7051d1f_3_cpu
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_2
  - libre2-11=2025.11.05=h0eb2380_0
  - librttopo=1.1.0=h5ff11c1_19
  - libsodium=1.0.20=hc70643c_0
  - libspatialite=5.1.0=h9d118f5_16
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h550210a_0
  - libutf8proc=2.11.0=h0b34c2f_0
  - libvorbis=1.3.7=h5112557_2
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxml2-devel=2.15.1=ha29bfb0_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.5=hfa2b4ca_0
  - llvmlite=0.45.1=py310hfe4b161_0
  - lxml=6.0.2=py310h095aac5_2
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markupsafe=3.0.3=py310hdb0e946_0
  - matplotlib=3.10.7=py310h5588dad_0
  - matplotlib-base=3.10.7=py310h0bdd906_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - minizip=4.0.10=h9fa1bad_0
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2024.2.2=h57928b3_16
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=he0c23c2_0
  - narwhals=2.12.0=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.62.1=py310h86ba7b5_0
  - numexpr=2.14.1=mkl_py310h4c4f63a_1
  - numpy=2.2.6=py310h4987827_0
  - openjpeg=2.5.4=h24db6dd_0
  - openpyxl=3.1.5=py310h5fa2519_2
  - openssl=3.6.0=h725018a_0
  - orc=2.2.1=h7414dfc_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310hed136d8_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.0.0=py310hfb50504_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.5.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - proj=9.6.2=h7990399_2
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psutil=7.1.3=py310h1637853_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pyarrow=22.0.0=py310h5588dad_0
  - pyarrow-core=22.0.0=py310hb6ca4c2_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyogrio=0.11.1=py310h2c68bc6_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.7.1=py310h61ea1ad_1
  - pyqt=5.15.11=py310hdf200a9_2
  - pyqt5-sip=12.17.0=py310h73ae2b4_2
  - pyside6=6.9.3=py310h96c60bd_1
  - pysocks=1.7.1=pyh09c184e_7
  - pytables=3.10.1=py310h36d347b_4
  - python=3.10.19=hc20f281_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-duckdb=1.4.1=py310h73ae2b4_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py310h282bd7d_1
  - pywinpty=2.0.15=py310h9e98ed7_1
  - pyyaml=6.0.3=py310hdb0e946_0
  - pyzmq=27.1.0=py310h535538e_0
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.15=hb098fff_6
  - qt6-main=6.9.3=ha0de62e_1
  - re2=2025.11.05=ha104f34_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.28.0=py310h034784e_1
  - scikit-learn=1.7.2=py310h21054b0_0
  - scipy=1.15.2=py310h15c175c_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.2=py310h57f9f94_0
  - sip=6.10.0=py310h73ae2b4_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlalchemy=2.0.44=py310h29418f3_0
  - sqlite=3.51.0=hdb435a2_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py310h8f3aa81_1
  - tbb=2021.13.0=hd094cb3_4
  - terminado=0.18.1=pyh5737063_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_2
  - toml=0.10.2=pyhd8ed1ab_2
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.2=py310h29418f3_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py310h29418f3_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - xerces-c=3.2.5=he0c23c2_2
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_2
  - zlib-ng=2.2.5=h32d8bfd_0
  - zstandard=0.25.0=py310h1637853_1
  - zstd=1.5.7=hbeecb71_2
prefix: C:\Users\crescentini\AppData\Local\miniconda3\envs\gtab-py
